name: Update Quote

on:
  workflow_dispatch:  # Manually trigger the workflow
  schedule:
    - cron: '*/1 * * * *'  # Run every 1 minute for testing

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Update to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # This is already correct
        with:
          node-version: '20'  # Ensure you're using Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Update Quote
        run: node update-quote.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.email "malikbilalakbar1@gmail.com"
          git config --global user.name "hafizbilalakbar"
          git add README.md
          git commit -m "Update README with daily quote" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hafizbilalakbar/hafizbilalakbar.git HEAD:main
